version: "3.7"
services:
  web:
    build: .    
    volumes: 
        - ./web:/var/www/html
    ports:
        - "80:80"
  db:
      image: mysql
      volumes:
          - ./base_Datos:/var/lib/mysql
      environment: 
          MYSQL_ROOT_PASSWORD: 12345
          MYSQL_DATABASE: docker_basedatos   
      ports: 
          - 3306:3306    

         

